apiVersion: v1
kind: Pod
metadata:
  name: node-exporter-pod
  labels:
    app: node-exporter
spec:
  containers:
  - name: node-exporter
    image: prom/node-exporter
    ports:
      - containerPort: 9100

